version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962829500930.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=962829500930.dkr.ecr.us-west-2.amazonaws.com/aws-testing
      - IMAGE_TAG=${CODEBUILD_WEBHOOK_TRIGGER#branch/}
      - printenv
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
